# SUMÁRIO

- [1. INFOS API DATAJUD](#1-infos-api-datajud)

- [EXEMPLOS DE CONSULTA INDIVIDUAL](#testes-consulta-individual)

### 1. INFOS API DATAJUD

#### ENDPOINT

- https://api-publica.datajud.cnj.jus.br/api_publica_tjsp/_search

#### TESTES CONSULTA INDIVIDUAL

[VOLTAR AO SUMÁRIO](#sumário)

### 1. CARREGAR PACOTES

In [1]:
import requests
import json
import ast

import pandas as pd
pd.set_option('display.max_rows', 100) 
import numpy as np

import concurrent.futures
from time import sleep
from tqdm import tqdm

In [2]:
API_KEY = "cDZHYzlZa0JadVREZDJCendQbXY6SkJlTzNjLV9TRENyQk1RdnFKZGRQdw=="
url = "https://api-publica.datajud.cnj.jus.br/api_publica_tjsp/_search"
headers = {
    'Authorization': f'ApiKey {API_KEY}',
    'Content-Type': 'application/json'
}

def consultar_processo(numero):
    payload = json.dumps({
        "query": {
            "match": {
                "numeroProcesso": numero
            }
        }
    })

    try:
        response = requests.post(url, headers=headers, data=payload, timeout=30)
        response.raise_for_status()
        data = response.json()

        resultados = []
        for hit in data.get("hits", {}).get("hits", []):
            registro = hit["_source"]
            #registro["_id"] = hit.get("_id")
            resultados.append(registro)

        return resultados

    except Exception as e:
        print(f"❌ Erro no processo {numero}: {e}")
        return []

def processar_em_lotes(lista, max_threads=5):
    todos_resultados = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_threads) as executor:
        futures = {executor.submit(consultar_processo, numero): numero for numero in lista}

        for future in tqdm(concurrent.futures.as_completed(futures), total=len(futures)):
            resultado = future.result()
            todos_resultados.extend(resultado)
            sleep(0.1)  

    return todos_resultados

In [7]:
lote001 = pd.read_parquet('./app/resultado-api/lotes/lote_001.parquet')
# lote1200 = pd.read_parquet('./app10/resultado-api/lotes/lote_1200.parquet')

In [8]:
lote001.columns.tolist()

['numeroProcesso',
 'classe',
 'sistema',
 'formato',
 'tribunal',
 'dataHoraUltimaAtualizacao',
 'grau',
 '@timestamp',
 'dataAjuizamento',
 'movimentos',
 'id',
 'nivelSigilo',
 'orgaoJulgador',
 'assuntos',
 'data_download']

In [9]:
consolidado = pd.read_parquet('./app/resultado-api/resultado_api_completo.parquet')

consolidado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1852 entries, 0 to 1851
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   numeroProcesso             1852 non-null   object
 1   classe                     1852 non-null   object
 2   sistema                    1852 non-null   object
 3   formato                    1852 non-null   object
 4   tribunal                   1852 non-null   object
 5   dataHoraUltimaAtualizacao  1852 non-null   object
 6   grau                       1852 non-null   object
 7   @timestamp                 1852 non-null   object
 8   dataAjuizamento            1852 non-null   object
 9   movimentos                 1825 non-null   object
 10  id                         1852 non-null   object
 11  nivelSigilo                1852 non-null   int64
 12  orgaoJulgador              1852 non-null   object
 13  assuntos                   1852 non-null   object
 14  data_download              1852 non-null   object
dtypes: int64(1), object(14)
memory usage: 217.2+ KB

In [ ]:
consolidado.head()

,numeroProcesso,classe,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,movimentos,id,nivelSigilo,orgaoJulgador,assuntos,data_download
0,15020035120248260408,"{'codigo': 10944, 'nome': 'Ação Penal - Proced...","{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2024-11-13T08:44:38.961Z,JE,2025-02-06T04:58:44.932854109Z,2024-07-16T17:22:38.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15020035120248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3475, 'nome': 'Abandono Intelectua...",2025-10-07 13:25:58
1,15020043620248260408,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}","{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-01-10T19:07:16.198Z,JE,2025-02-07T18:00:07.192953222Z,2024-07-16T17:23:41.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15020043620248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3402, 'nome': 'Ameaça '}]",2025-10-07 13:25:58
2,15019272720248260408,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}","{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-02-06T01:50:19.685Z,JE,2025-02-10T19:12:56.822004782Z,2024-07-05T17:14:09.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019272720248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3386, 'nome': 'Leve'}]",2025-10-07 13:25:58
3,15019281220248260408,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}","{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2024-11-13T08:45:08.875Z,JE,2025-02-06T04:59:01.819538222Z,2024-07-06T10:09:51.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019281220248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3632, 'nome': 'Crimes de Trânsito'}]",2025-10-07 13:25:58
4,15019142820248260408,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}","{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2024-08-27T01:40:36.496Z,JE,2025-06-16T19:09:05.169414101Z,2024-07-05T11:10:02.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019142820248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3402, 'nome': 'Ameaça '}]",2025-10-07 13:25:58

In [18]:
df = pd.DataFrame(consultar_processo('00014874419948260445'))

df

,classe,numeroProcesso,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,movimentos,id,nivelSigilo,orgaoJulgador,assuntos
0,"{'codigo': 108, 'nome': 'Falência de Empresári...",00014874419948260445,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 2, 'nome': 'Físico'}",TJSP,2024-08-27T20:55:40.223Z,G1,2025-06-17T07:32:59.967679806Z,1994-01-10T00:00:00.000Z,"[{'codigo': 981, 'nome': 'Recebimento', 'dataH...",TJSP_108_G1_10053_00014874419948260445,0,"{'codigo': 10053, 'nome': '03 CIVEL DE PINDAMO...","[{'codigo': 4993, 'nome': 'Recuperação judicia..."

In [48]:
df

,classe,numeroProcesso,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,movimentos,id,nivelSigilo,orgaoJulgador,assuntos
0,"{'codigo': 108, 'nome': 'Falência de Empresári...",00014874419948260445,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 2, 'nome': 'Físico'}",TJSP,2024-08-27T20:55:40.223Z,G1,2025-06-17T07:32:59.967679806Z,1994-01-10T00:00:00.000Z,"[{'codigo': 981, 'nome': 'Recebimento', 'dataH...",TJSP_108_G1_10053_00014874419948260445,0,"{'codigo': 10053, 'nome': '03 CIVEL DE PINDAMO...","[{'codigo': 4993, 'nome': 'Recuperação judicia..."

#### 2. Função para expandir colunas com dicionários

In [49]:
def expandir_colunas(df, colunas_alvo, chaves=['codigo', 'nome'], como_string=True, separador='|'):
    """
    Expande colunas contendo listas de dicionários (ou dicts), criando novas colunas para cada chave.
    Os valores podem ser retornados como listas ou strings separadas por vírgula (default).
    Mantém a ordem original das colunas, inserindo as novas logo após a original.
    """
    df_exp = df.copy()
    novas_colunas = {}

    def extrair_primeiros(lista_ou_dict, chave):
        if isinstance(lista_ou_dict, dict):
            val = lista_ou_dict.get(chave, None)
            return str(val) if como_string else val
        elif isinstance(lista_ou_dict, list):
            try:
                valores = [str(d.get(chave)) for d in lista_ou_dict if isinstance(d, dict)]
                return separador.join(valores) if como_string else valores
            except:
                return None
        return None

    for col in colunas_alvo:
        if col not in df_exp.columns:
            continue
        valores_expandidos = df_exp[col].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
        for chave in chaves:
            nova_coluna = f"{col}_{chave}"
            # Garante que só cria a coluna uma vez
            if nova_coluna not in novas_colunas:
                novas_colunas[nova_coluna] = valores_expandidos.apply(lambda v: extrair_primeiros(v, chave))

    # Insere as novas colunas logo após cada coluna original
    for col in colunas_alvo:
        if col not in df_exp.columns:
            continue
        idx_col = df_exp.columns.get_loc(col)
        insert_at = idx_col + 1
        for chave in chaves:
            nova_coluna = f"{col}_{chave}"
            if nova_coluna in df_exp.columns:
                continue  # Não sobrescreve se já existe
            df_exp.insert(insert_at, nova_coluna, novas_colunas[nova_coluna])
            insert_at += 1

    if 'numeroProcesso' in df_exp.columns:
        cols = df_exp.columns.tolist()
        cols.remove('numeroProcesso')
        df_exp = df_exp[['numeroProcesso'] + cols]


    return df_exp

In [31]:
lote001 = pd.read_parquet('./app/resultado-api/lotes/lote_001.parquet')

lote001.head()

,classe,numeroProcesso,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,movimentos,id,nivelSigilo,orgaoJulgador,assuntos,_id,data_download
0,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15020043620248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-01-10T19:07:16.198Z,JE,2025-02-07T18:00:07.192953222Z,2024-07-16T17:23:41.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15020043620248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3402, 'nome': 'Ameaça '}]",TJSP_JE_15020043620248260408,2025-09-03 11:52:29
1,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15019991420248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2024-08-27T01:40:01.997Z,JE,2025-06-16T19:08:53.811380883Z,2024-07-16T17:13:45.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019991420248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3402, 'nome': 'Ameaça '}]",TJSP_JE_15019991420248260408,2025-09-03 11:52:29
2,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15019272720248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-02-06T01:50:19.685Z,JE,2025-02-10T19:12:56.822004782Z,2024-07-05T17:14:09.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019272720248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3386, 'nome': 'Leve'}]",TJSP_JE_15019272720248260408,2025-09-03 11:52:29
3,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15019982920248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-01-10T19:07:09.830Z,JE,2025-02-07T18:00:06.171637952Z,2024-07-16T17:11:05.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019982920248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3386, 'nome': 'Leve'}]",TJSP_JE_15019982920248260408,2025-09-03 11:52:29
4,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15019142820248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2024-08-27T01:40:36.496Z,JE,2025-06-16T19:09:05.169414101Z,2024-07-05T11:10:02.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019142820248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3402, 'nome': 'Ameaça '}]",TJSP_JE_15019142820248260408,2025-09-03 11:52:29

In [32]:
[lote001.assuntos[i] for i in range(len(lote001))]

["[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3386, 'nome': 'Leve'}]",
 "[{'codigo': 3386, 'nome': 'Leve'}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3632, 'nome': 'Crimes de Trânsito'}]",
 "[{'codigo': 3632, 'nome': 'Crimes de Trânsito'}]",
 "[{'codigo': 3435, 'nome': 'Receptação'}]",
 "[{'codigo': 3475, 'nome': 'Abandono Intelectual'}]",
 "[{'codigo': 3572, 'nome': 'Desobediência '}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3395, 'nome': 'Calúnia'}]",
 "[{'codigo': 3386, 'nome': 'Leve'}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3397, 'nome': 'Injúria'}]",
 "[{'codigo': 3632, 'nome': 'Crimes de Trânsito'}]",
 "[{'codigo': 3431, 'nome': 'Estelionato'}]",
 "[{'codigo': 3692, 'nome': 'Contravenções Penais'}]",
 "[{'codigo': 3397, 'nome': 'Injúria'}]",
 "[{'codigo': 3692, 'nome': 'Contravenções Penais'}]",
 "[{'codigo': 3692, 'nome': 'Contravenções Penais'}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3386, 'nome': 'Leve'}]",
 "[{'codigo': 3386, 'nome': 'Leve'}]",
 "[{'codigo': 3435, 'nome': 'Receptação'}]",
 "[{'codigo': 3395, 'nome': 'Calúnia'}]",
 "[{'codigo': 3397, 'nome': 'Injúria'}]",
 "[{'codigo': 3397, 'nome': 'Injúria'}]",
 "[{'codigo': 3423, 'nome': 'Alteração de limites '}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3692, 'nome': 'Contravenções Penais'}]",
 "[{'codigo': 3692, 'nome': 'Contravenções Penais'}]",
 "[{'codigo': 3692, 'nome': 'Contravenções Penais'}]",
 "[{'codigo': 3692, 'nome': 'Contravenções Penais'}]",
 "[{'codigo': 3406, 'nome': 'Violação de domicílio '}]",
 "[{'codigo': 3406, 'nome': 'Violação de domicílio '}]",
 "[{'codigo': 3632, 'nome': 'Crimes de Trânsito'}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3396, 'nome': 'Difamação'}]",
 "[{'codigo': 3572, 'nome': 'Desobediência '}]",
 "[{'codigo': 3386, 'nome': 'Leve'}]",
 "[{'codigo': 3692, 'nome': 'Contravenções Penais'}]",
 "[{'codigo': 3397, 'nome': 'Injúria'}]",
 "[{'codigo': 3692, 'nome': 'Contravenções Penais'}]",
 "[{'codigo': 5872, 'nome': 'Crimes Praticados por Particular Contra a Administração em Geral'}]",
 "[{'codigo': 5872, 'nome': 'Crimes Praticados por Particular Contra a Administração em Geral'}]",
 "[{'codigo': 3581, 'nome': 'Exercício arbitrário das próprias razões '}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3397, 'nome': 'Injúria'}]",
 "[{'codigo': 10296, 'nome': 'Descontos Indevidos'}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 3402, 'nome': 'Ameaça '}]",
 "[{'codigo': 10296, 'nome': 'Descontos Indevidos'}]",
 "[{'codigo': 10296, 'nome': 'Descontos Indevidos'}]",
 "[{'codigo': 10296, 'nome': 'Descontos Indevidos'}]",
 "[{'codigo': 10306, 'nome': 'Auxílio-transporte'}]",
 "[{'codigo': 4703, 'nome': 'Defeito, nulidade ou anulação'}]",
 "[{'codigo': 10305, 'nome': 'Gratificações de Atividade'}]",
 "[{'codigo': 10277, 'nome': 'Averbação / Contagem de Tempo Especial'}]",
 "[{'codigo': 10229, 'nome': 'Remoção'}]",
 "[{'codigo': 10229, 'nome': 'Remoção'}]",
 "[{'codigo': 10229, 'nome': 'Remoção'}]",
 "[{'codigo': 10296, 'nome': 'Descontos Indevidos'}]",
 "[{'codigo': 10229, 'nome': 'Remoção'}]",
 "[{'codigo': 10229, 'nome': 'Remoção'}]",
 "[{'codigo': 10229, 'nome': 'Remoção'}]",
 "[{'codigo': 10296, 'nome': 'Descontos Indevidos'}]",
 "[{'codigo': 9996, 'nome': 'Acidente de Trânsito'}]",
 "[{'codigo': 10302, 'nome': 'Adicional por Tempo de Serviço'}]",
 "[{'codigo': 4842, 'nome': 'Reajuste de Prestações'}]",
 "[{'codigo': 6007, 'nome': 'Repetição de indébito'}]",
 "[{'codigo': 10236, 'nome': 'Promoção / Ascensão'}]",
 "[{'codigo': 10236, 'nome': 'Promoção / Ascensão'}]",
 "[{'codigo': 10305, 'nome': 'Gratificações de Atividade'}]",
 "[{'codigo': 10287, 'nome': 'Jornada de Trabalho'}]",
 "[{'codigo': 10305, 'nome': 'Gratificações de Atividade'}]",
 "[{'codigo': 10288, 'nome': 'Sistema Remuneratório e Benefícios'}]",
 "[{'codigo': 7698, 'nome': 'Perdas e Danos'}, {'codigo': 10338, 'nome': 'Gratificações e Adicionais'}]",
 "[{'codigo': 10287, 'nome': 'Jornada de Trabalho'}]",
 "[{'codigo': 10671, 'nome': 'Obrigação de Fazer / Não Fazer'}]",
 "[{'codigo': 10338, 'nome': 'Gratificações e Adicionais'}]",
 "[{'codigo': 10671, 'nome': 'Obrigação de Fazer / Não Fazer'}]",
 "[{'codigo': 10338, 'nome': 'Gratificações e Adicionais'}]",
 "[{'codigo': 4840, 'nome': 'Equivalência salarial'}]",
 "[{'codigo': 10287, 'nome': 'Jornada de Trabalho'}]",
 "[{'codigo': 10296, 'nome': 'Descontos Indevidos'}]",
 "[{'codigo': 10296, 'nome': 'Descontos Indevidos'}]",
 "[{'codigo': 10288, 'nome': 'Sistema Remuneratório e Benefícios'}]"]

In [33]:
colunas = ['classe', 'sistema', 'formato', 'orgaoJulgador', 'assuntos']
df_expandido = expandir_colunas(lote001, colunas)

df_expandido.head()

,numeroProcesso,classe,classe_codigo,classe_nome,sistema,sistema_codigo,sistema_nome,formato,formato_codigo,formato_nome,...,id,nivelSigilo,orgaoJulgador,orgaoJulgador_codigo,orgaoJulgador_nome,assuntos,assuntos_codigo,assuntos_nome,_id,data_download
0,15020043620248260408,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",278,Termo Circunstanciado,"{'codigo': 3, 'nome': 'SAJ'}",3,SAJ,"{'codigo': 1, 'nome': 'Eletrônico'}",1,Eletrônico,...,TJSP_JE_15020043620248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...",10002,01 CRIMINAL DE OURINHOS,"[{'codigo': 3402, 'nome': 'Ameaça '}]",3402,Ameaça,TJSP_JE_15020043620248260408,2025-09-03 11:52:29
1,15019991420248260408,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",278,Termo Circunstanciado,"{'codigo': 3, 'nome': 'SAJ'}",3,SAJ,"{'codigo': 1, 'nome': 'Eletrônico'}",1,Eletrônico,...,TJSP_JE_15019991420248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...",10002,01 CRIMINAL DE OURINHOS,"[{'codigo': 3402, 'nome': 'Ameaça '}]",3402,Ameaça,TJSP_JE_15019991420248260408,2025-09-03 11:52:29
2,15019272720248260408,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",278,Termo Circunstanciado,"{'codigo': 3, 'nome': 'SAJ'}",3,SAJ,"{'codigo': 1, 'nome': 'Eletrônico'}",1,Eletrônico,...,TJSP_JE_15019272720248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...",10002,01 CRIMINAL DE OURINHOS,"[{'codigo': 3386, 'nome': 'Leve'}]",3386,Leve,TJSP_JE_15019272720248260408,2025-09-03 11:52:29
3,15019982920248260408,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",278,Termo Circunstanciado,"{'codigo': 3, 'nome': 'SAJ'}",3,SAJ,"{'codigo': 1, 'nome': 'Eletrônico'}",1,Eletrônico,...,TJSP_JE_15019982920248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...",10002,01 CRIMINAL DE OURINHOS,"[{'codigo': 3386, 'nome': 'Leve'}]",3386,Leve,TJSP_JE_15019982920248260408,2025-09-03 11:52:29
4,15019142820248260408,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",278,Termo Circunstanciado,"{'codigo': 3, 'nome': 'SAJ'}",3,SAJ,"{'codigo': 1, 'nome': 'Eletrônico'}",1,Eletrônico,...,TJSP_JE_15019142820248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...",10002,01 CRIMINAL DE OURINHOS,"[{'codigo': 3402, 'nome': 'Ameaça '}]",3402,Ameaça,TJSP_JE_15019142820248260408,2025-09-03 11:52:29

In [34]:
df_expandido.columns

Index(['numeroProcesso', 'classe', 'classe_codigo', 'classe_nome', 'sistema',
       'sistema_codigo', 'sistema_nome', 'formato', 'formato_codigo',
       'formato_nome', 'tribunal', 'dataHoraUltimaAtualizacao', 'grau',
       '@timestamp', 'dataAjuizamento', 'movimentos', 'id', 'nivelSigilo',
       'orgaoJulgador', 'orgaoJulgador_codigo', 'orgaoJulgador_nome',
       'assuntos', 'assuntos_codigo', 'assuntos_nome', '_id', 'data_download'],
      dtype='object')

In [35]:
df_expandido[df_expandido['numeroProcesso'] == '10018662020248260411'][['assuntos','assuntos_codigo','assuntos_nome']]

,assuntos,assuntos_codigo,assuntos_nome
78,"[{'codigo': 7698, 'nome': 'Perdas e Danos'}, {...",7698|10338,Perdas e Danos|Gratificações e Adicionais

In [36]:
lote001.head()

,classe,numeroProcesso,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,movimentos,id,nivelSigilo,orgaoJulgador,assuntos,_id,data_download
0,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15020043620248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-01-10T19:07:16.198Z,JE,2025-02-07T18:00:07.192953222Z,2024-07-16T17:23:41.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15020043620248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3402, 'nome': 'Ameaça '}]",TJSP_JE_15020043620248260408,2025-09-03 11:52:29
1,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15019991420248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2024-08-27T01:40:01.997Z,JE,2025-06-16T19:08:53.811380883Z,2024-07-16T17:13:45.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019991420248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3402, 'nome': 'Ameaça '}]",TJSP_JE_15019991420248260408,2025-09-03 11:52:29
2,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15019272720248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-02-06T01:50:19.685Z,JE,2025-02-10T19:12:56.822004782Z,2024-07-05T17:14:09.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019272720248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3386, 'nome': 'Leve'}]",TJSP_JE_15019272720248260408,2025-09-03 11:52:29
3,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15019982920248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-01-10T19:07:09.830Z,JE,2025-02-07T18:00:06.171637952Z,2024-07-16T17:11:05.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019982920248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3386, 'nome': 'Leve'}]",TJSP_JE_15019982920248260408,2025-09-03 11:52:29
4,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15019142820248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2024-08-27T01:40:36.496Z,JE,2025-06-16T19:09:05.169414101Z,2024-07-05T11:10:02.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15019142820248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3402, 'nome': 'Ameaça '}]",TJSP_JE_15019142820248260408,2025-09-03 11:52:29

In [18]:
lote001['movimentos'][0]

array([{'codigo': 26, 'complementosTabelados': array([{'codigo': 2, 'descricao': 'tipo_de_distribuicao_redistribuicao', 'nome': 'sorteio', 'valor': 2}],
             dtype=object), 'dataHora': '2024-07-16T17:24:07.000Z', 'nome': 'Distribuição'}                                                             ,
       {'codigo': 581, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Outros documentos', 'valor': 80}],
             dtype=object), 'dataHora': '2024-07-16T17:28:18.000Z', 'nome': 'Documento'}                                                          ,
       {'codigo': 11383, 'complementosTabelados': None, 'dataHora': '2024-07-17T10:42:52.000Z', 'nome': 'Ato ordinatório'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-07-17T10:43:09.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 85, 'complementosTabelados': array([{'codigo': 19, 'descricao': 'tipo_de_peticao', 'nome': 'Petição (outras)', 'valor': 57}],
             dtype=object), 'dataHora': '2024-07-17T20:11:25.000Z', 'nome': 'Petição'}                                                         ,
       {'codigo': 11383, 'complementosTabelados': None, 'dataHora': '2024-07-17T20:12:09.000Z', 'nome': 'Ato ordinatório'},
       {'codigo': 85, 'complementosTabelados': array([{'codigo': 19, 'descricao': 'tipo_de_peticao', 'nome': 'Petição (outras)', 'valor': 57}],
             dtype=object), 'dataHora': '2024-07-17T20:13:48.000Z', 'nome': 'Petição'}                                                         ,
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-07-17T21:23:58.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 51, 'complementosTabelados': array([{'codigo': 3, 'descricao': 'tipo_de_conclusao', 'nome': 'para despacho', 'valor': 5}],
             dtype=object), 'dataHora': '2024-07-18T09:25:45.000Z', 'nome': 'Conclusão'}                                                    ,
       {'codigo': 51, 'complementosTabelados': array([{'codigo': 3, 'descricao': 'tipo_de_conclusao', 'nome': 'para despacho', 'valor': 5}],
             dtype=object), 'dataHora': '2024-07-18T10:04:22.000Z', 'nome': 'Conclusão'}                                                    ,
       {'codigo': 11010, 'complementosTabelados': None, 'dataHora': '2024-07-18T10:40:58.000Z', 'nome': 'Mero expediente'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-07-19T11:14:21.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Ofício', 'valor': 79}],
             dtype=object), 'dataHora': '2024-07-22T10:50:45.000Z', 'nome': 'Expedição de documento'}                                 ,
       {'codigo': 85, 'complementosTabelados': array([{'codigo': 19, 'descricao': 'tipo_de_peticao', 'nome': 'Petição (outras)', 'valor': 57}],
             dtype=object), 'dataHora': '2024-08-12T15:43:23.000Z', 'nome': 'Petição'}                                                         ,
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-11-18T13:10:53.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 581, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Outros documentos', 'valor': 80}],
             dtype=object), 'dataHora': '2024-11-18T13:15:00.000Z', 'nome': 'Documento'}                                                          ,
       {'codigo': 11383, 'complementosTabelados': None, 'dataHora': '2024-11-18T13:16:28.000Z', 'nome': 'Ato ordinatório'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-11-18T13:16:52.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 85, 'complementosTabelados': array([{'codigo': 19, 'descricao': 'tipo_de_peticao', 'nome': 'Petição (outras)', 'valor': 57}],
             dtype=object), 'dataHora': '2024-11-18T21:15:08.000Z', 'nome': 'Petição'}                                                         ,
       {'codigo': 51, 'complementosTabelados': array([{'codigo': 3, 'descricao': 'tipo_de_conclusao', 'nome': 'para despacho', 'valor': 5}],
             dtype=object), 'dataHora': '2024-11-19T10:01:18.000Z', 'nome': 'Conclusão'}                                                    ,
       {'codigo': 51, 'complementosTabelados': array([{'codigo': 3, 'descricao': 'tipo_de_conclusao', 'nome': 'para julgamento', 'valor': 36}],
             dtype=object), 'dataHora': '2024-11-19T13:26:04.000Z', 'nome': 'Conclusão'}                                                       ,
       {'codigo': 11879, 'complementosTabelados': None, 'dataHora': '2024-11-19T14:27:57.000Z', 'nome': 'Decadência ou perempção'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-11-25T14:32:15.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-12-17T09:19:41.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 11383, 'complementosTabelados': None, 'dataHora': '2024-12-17T09:26:20.000Z', 'nome': 'Ato ordinatório'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Ofício', 'valor': 79}],
             dtype=object), 'dataHora': '2024-12-17T10:13:16.000Z', 'nome': 'Expedição de documento'}                                 ,
       {'codigo': 246, 'complementosTabelados': None, 'dataHora': '2024-12-17T14:22:53.000Z', 'nome': 'Definitivo'}],
      dtype=object)

In [53]:
def extrair_movimentos_completos (df: pd.DataFrame) -> pd.DataFrame:
    todos_movimentos = []

    for _, row in df.iterrows():
        processo_id = row.get("id")
        numero_processo = row.get("numeroProcesso")
        movimentos = row.get("movimentos")
        data_download = row.get("data_download")

        if not isinstance(movimentos, (list, np.ndarray)):
            continue

        for mov in movimentos:
            movimento_info = {
                "id": processo_id,
                "numeroProcesso": numero_processo,
                "movimentos_codigo": mov.get("codigo"),
                "movimentos_nome": mov.get("nome"),
                "movimentos_dataHora": mov.get("dataHora"),
                "movimentos_orgaoJulgador": mov.get("orgaoJulgador"),
                "movimentos_orgaoJulgador_codigoOrgao": None,
                "movimentos_orgaoJulgador_nomeOrgao": None,
                "movimentos_complementosTabelados": None,
                "movimentos_complementosTabelados_codigo": None,
                "movimentos_complementosTabelados_descricao": None,
                "movimentos_complementosTabelados_valor": None,
                "movimentos_complementosTabelados_nome": None,
                "data_download": data_download
            }

            # Orgao julgador (dict)
            orgao = mov.get("orgaoJulgador")
            if isinstance(orgao, dict):
                movimento_info["movimentos_orgaoJulgador_codigoOrgao"] = orgao.get("codigoOrgao")
                movimento_info["movimentos_orgaoJulgador_nomeOrgao"] = orgao.get("nomeOrgao")

            # Complementos Tabelados (list ou ndarray de dicts)
            complementos = mov.get("complementosTabelados")

            if isinstance(complementos, np.ndarray):
                complementos = complementos.tolist()

            if isinstance(complementos, list) and len(complementos) > 0:
                for comp in complementos:
                    comp_info = movimento_info.copy()
                    comp_info["movimentos_complementosTabelados"] = complementos
                    comp_info["movimentos_complementosTabelados_codigo"] = comp.get("codigo")
                    comp_info["movimentos_complementosTabelados_descricao"] = comp.get("descricao")
                    comp_info["movimentos_complementosTabelados_valor"] = comp.get("valor")
                    comp_info["movimentos_complementosTabelados_nome"] = comp.get("nome")
                    todos_movimentos.append(comp_info)
            else:
                # Sem complementos, mas ainda queremos registrar o movimento
                todos_movimentos.append(movimento_info)

    df_movimentos = pd.DataFrame(todos_movimentos)

    if not df_movimentos.empty and "movimentos_dataHora" in df_movimentos.columns:
        df_movimentos["movimentos_dataHora"] = pd.to_datetime(df_movimentos["movimentos_dataHora"], errors="coerce")
        ordem_id_original = pd.CategoricalDtype(categories = df['id'].to_list(),ordered=True)
        df_movimentos['id'] = df_movimentos['id'].astype(ordem_id_original)

        df_movimentos = df_movimentos.sort_values(by=['id', "movimentos_dataHora"], ascending=[True,False])

        df_movimentos = df_movimentos.reset_index(drop=True)
    
    return df_movimentos

In [51]:
lote001.iloc[[0]]

,classe,numeroProcesso,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,movimentos,id,nivelSigilo,orgaoJulgador,assuntos,_id,data_download
0,"{'codigo': 278, 'nome': 'Termo Circunstanciado'}",15020043620248260408,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-01-10T19:07:16.198Z,JE,2025-02-07T18:00:07.192953222Z,2024-07-16T17:23:41.000Z,"[{'codigo': 26, 'complementosTabelados': [{'co...",TJSP_JE_15020043620248260408,0,"{'codigo': 10002, 'nome': '01 CRIMINAL DE OURI...","[{'codigo': 3402, 'nome': 'Ameaça '}]",TJSP_JE_15020043620248260408,2025-09-03 11:52:29

In [21]:
lote001.iloc[[0]].movimentos[0]

array([{'codigo': 26, 'complementosTabelados': array([{'codigo': 2, 'descricao': 'tipo_de_distribuicao_redistribuicao', 'nome': 'sorteio', 'valor': 2}],
             dtype=object), 'dataHora': '2024-07-16T17:24:07.000Z', 'nome': 'Distribuição'}                                                             ,
       {'codigo': 581, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Outros documentos', 'valor': 80}],
             dtype=object), 'dataHora': '2024-07-16T17:28:18.000Z', 'nome': 'Documento'}                                                          ,
       {'codigo': 11383, 'complementosTabelados': None, 'dataHora': '2024-07-17T10:42:52.000Z', 'nome': 'Ato ordinatório'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-07-17T10:43:09.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 85, 'complementosTabelados': array([{'codigo': 19, 'descricao': 'tipo_de_peticao', 'nome': 'Petição (outras)', 'valor': 57}],
             dtype=object), 'dataHora': '2024-07-17T20:11:25.000Z', 'nome': 'Petição'}                                                         ,
       {'codigo': 11383, 'complementosTabelados': None, 'dataHora': '2024-07-17T20:12:09.000Z', 'nome': 'Ato ordinatório'},
       {'codigo': 85, 'complementosTabelados': array([{'codigo': 19, 'descricao': 'tipo_de_peticao', 'nome': 'Petição (outras)', 'valor': 57}],
             dtype=object), 'dataHora': '2024-07-17T20:13:48.000Z', 'nome': 'Petição'}                                                         ,
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-07-17T21:23:58.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 51, 'complementosTabelados': array([{'codigo': 3, 'descricao': 'tipo_de_conclusao', 'nome': 'para despacho', 'valor': 5}],
             dtype=object), 'dataHora': '2024-07-18T09:25:45.000Z', 'nome': 'Conclusão'}                                                    ,
       {'codigo': 51, 'complementosTabelados': array([{'codigo': 3, 'descricao': 'tipo_de_conclusao', 'nome': 'para despacho', 'valor': 5}],
             dtype=object), 'dataHora': '2024-07-18T10:04:22.000Z', 'nome': 'Conclusão'}                                                    ,
       {'codigo': 11010, 'complementosTabelados': None, 'dataHora': '2024-07-18T10:40:58.000Z', 'nome': 'Mero expediente'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-07-19T11:14:21.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Ofício', 'valor': 79}],
             dtype=object), 'dataHora': '2024-07-22T10:50:45.000Z', 'nome': 'Expedição de documento'}                                 ,
       {'codigo': 85, 'complementosTabelados': array([{'codigo': 19, 'descricao': 'tipo_de_peticao', 'nome': 'Petição (outras)', 'valor': 57}],
             dtype=object), 'dataHora': '2024-08-12T15:43:23.000Z', 'nome': 'Petição'}                                                         ,
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-11-18T13:10:53.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 581, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Outros documentos', 'valor': 80}],
             dtype=object), 'dataHora': '2024-11-18T13:15:00.000Z', 'nome': 'Documento'}                                                          ,
       {'codigo': 11383, 'complementosTabelados': None, 'dataHora': '2024-11-18T13:16:28.000Z', 'nome': 'Ato ordinatório'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-11-18T13:16:52.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 85, 'complementosTabelados': array([{'codigo': 19, 'descricao': 'tipo_de_peticao', 'nome': 'Petição (outras)', 'valor': 57}],
             dtype=object), 'dataHora': '2024-11-18T21:15:08.000Z', 'nome': 'Petição'}                                                         ,
       {'codigo': 51, 'complementosTabelados': array([{'codigo': 3, 'descricao': 'tipo_de_conclusao', 'nome': 'para despacho', 'valor': 5}],
             dtype=object), 'dataHora': '2024-11-19T10:01:18.000Z', 'nome': 'Conclusão'}                                                    ,
       {'codigo': 51, 'complementosTabelados': array([{'codigo': 3, 'descricao': 'tipo_de_conclusao', 'nome': 'para julgamento', 'valor': 36}],
             dtype=object), 'dataHora': '2024-11-19T13:26:04.000Z', 'nome': 'Conclusão'}                                                       ,
       {'codigo': 11879, 'complementosTabelados': None, 'dataHora': '2024-11-19T14:27:57.000Z', 'nome': 'Decadência ou perempção'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-11-25T14:32:15.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Certidão', 'valor': 107}],
             dtype=object), 'dataHora': '2024-12-17T09:19:41.000Z', 'nome': 'Expedição de documento'}                                    ,
       {'codigo': 11383, 'complementosTabelados': None, 'dataHora': '2024-12-17T09:26:20.000Z', 'nome': 'Ato ordinatório'},
       {'codigo': 60, 'complementosTabelados': array([{'codigo': 4, 'descricao': 'tipo_de_documento', 'nome': 'Ofício', 'valor': 79}],
             dtype=object), 'dataHora': '2024-12-17T10:13:16.000Z', 'nome': 'Expedição de documento'}                                 ,
       {'codigo': 246, 'complementosTabelados': None, 'dataHora': '2024-12-17T14:22:53.000Z', 'nome': 'Definitivo'}],
      dtype=object)

In [52]:
def extrair_movimentos_completos (df: pd.DataFrame) -> pd.DataFrame:
    todos_movimentos = []

    for _, row in df.iterrows():
        processo_id = row.get("_id")
        numero_processo = row.get("numeroProcesso")
        movimentos = row.get("movimentos")
        data_download = row.get("data_download")

        if not isinstance(movimentos, (list, np.ndarray)):
            continue

        for mov in movimentos:
            movimento_info = {
                "_id": processo_id,
                "numeroProcesso": numero_processo,
                "movimentos_codigo": mov.get("codigo"),
                "movimentos_nome": mov.get("nome"),
                "movimentos_dataHora": mov.get("dataHora"),
                "movimentos_orgaoJulgador": mov.get("orgaoJulgador"),
                "movimentos_orgaoJulgador_codigoOrgao": None,
                "movimentos_orgaoJulgador_nomeOrgao": None,
                "movimentos_complementosTabelados": None,
                "movimentos_complementosTabelados_codigo": None,
                "movimentos_complementosTabelados_descricao": None,
                "movimentos_complementosTabelados_valor": None,
                "movimentos_complementosTabelados_nome": None,
                "data_download": data_download
            }

            # Orgao julgador (dict)
            orgao = mov.get("orgaoJulgador")
            if isinstance(orgao, dict):
                movimento_info["movimentos_orgaoJulgador_codigoOrgao"] = orgao.get("codigoOrgao")
                movimento_info["movimentos_orgaoJulgador_nomeOrgao"] = orgao.get("nomeOrgao")

            # Complementos Tabelados (list ou ndarray de dicts)
            complementos = mov.get("complementosTabelados")

            if isinstance(complementos, np.ndarray):
                complementos = complementos.tolist()

            if isinstance(complementos, list) and len(complementos) > 0:
                for comp in complementos:
                    comp_info = movimento_info.copy()
                    comp_info["movimentos_complementosTabelados"] = complementos
                    comp_info["movimentos_complementosTabelados_codigo"] = comp.get("codigo")
                    comp_info["movimentos_complementosTabelados_descricao"] = comp.get("descricao")
                    comp_info["movimentos_complementosTabelados_valor"] = comp.get("valor")
                    comp_info["movimentos_complementosTabelados_nome"] = comp.get("nome")
                    todos_movimentos.append(comp_info)
            else:
                # Sem complementos, mas ainda queremos registrar o movimento
                todos_movimentos.append(movimento_info)

    df_movimentos = pd.DataFrame(todos_movimentos)

    if not df_movimentos.empty and "movimentos_dataHora" in df_movimentos.columns:
        df_movimentos["movimentos_dataHora"] = pd.to_datetime(df_movimentos["movimentos_dataHora"], errors="coerce")
        ordem_id_original = pd.CategoricalDtype(categories = df['_id'].to_list(),ordered=True)
        df_movimentos['_id'] = df_movimentos['_id'].astype(ordem_id_original)

        df_movimentos = df_movimentos.sort_values(by=['_id', "movimentos_dataHora"], ascending=[True,False])
        
        df_movimentos = df_movimentos.reset_index(drop=True)
    
    return df_movimentos

In [54]:
df

,classe,numeroProcesso,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,movimentos,id,nivelSigilo,orgaoJulgador,assuntos
0,"{'codigo': 108, 'nome': 'Falência de Empresári...",00014874419948260445,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 2, 'nome': 'Físico'}",TJSP,2024-08-27T20:55:40.223Z,G1,2025-06-17T07:32:59.967679806Z,1994-01-10T00:00:00.000Z,"[{'codigo': 981, 'nome': 'Recebimento', 'dataH...",TJSP_108_G1_10053_00014874419948260445,0,"{'codigo': 10053, 'nome': '03 CIVEL DE PINDAMO...","[{'codigo': 4993, 'nome': 'Recuperação judicia..."

In [55]:
df_movs = extrair_movimentos_completos(df)
# df_movs[['id','numeroProcesso','movimentos_dataHora','movimentos_nome']].sort_values(by=['movimentos_dataHora'], ascending=True).head(5)

In [57]:
df_movs.head(20)

,id,numeroProcesso,movimentos_codigo,movimentos_nome,movimentos_dataHora,movimentos_orgaoJulgador,movimentos_orgaoJulgador_codigoOrgao,movimentos_orgaoJulgador_nomeOrgao,movimentos_complementosTabelados,movimentos_complementosTabelados_codigo,movimentos_complementosTabelados_descricao,movimentos_complementosTabelados_valor,movimentos_complementosTabelados_nome,data_download
0,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,123,Remessa,2024-03-15 12:47:58+00:00,None,None,None,"[{'codigo': 18, 'valor': 38, 'nome': 'em grau ...",18.0,motivo_da_remessa,38.0,em grau de recurso,None
1,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,85,Petição,2023-12-13 14:11:17+00:00,None,None,None,"[{'codigo': 19, 'valor': 57, 'nome': 'Petição ...",19.0,tipo_de_peticao,57.0,Petição (outras),None
2,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,92,Publicação,2023-11-02 02:21:54+00:00,None,None,None,None,NaN,None,NaN,None,None
3,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,123,Remessa,2023-11-01 13:38:53+00:00,None,None,None,"[{'codigo': 18, 'valor': 40, 'nome': 'outros m...",18.0,motivo_da_remessa,40.0,outros motivos,None
4,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,11383,Ato ordinatório,2023-11-01 12:42:08+00:00,None,None,None,None,NaN,None,NaN,None,None
5,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,132,Recebimento,2023-11-01 10:31:57+00:00,None,None,None,None,NaN,None,NaN,None,None
6,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,493,Entrega em carga/vista,2023-10-30 11:26:20+00:00,None,None,None,None,NaN,None,NaN,None,None
7,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,85,Petição,2023-10-27 16:11:23+00:00,None,None,None,"[{'codigo': 19, 'valor': 57, 'nome': 'Petição ...",19.0,tipo_de_peticao,57.0,Petição (outras),None
8,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,60,Expedição de documento,2023-10-27 16:10:39+00:00,None,None,None,"[{'codigo': 4, 'valor': 107, 'nome': 'Certidão...",4.0,tipo_de_documento,107.0,Certidão,None
9,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,60,Expedição de documento,2023-10-27 16:10:26+00:00,None,None,None,"[{'codigo': 4, 'valor': 107, 'nome': 'Certidão...",4.0,tipo_de_documento,107.0,Certidão,None
10,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,92,Publicação,2023-10-03 00:01:06+00:00,None,None,None,None,NaN,None,NaN,None,None
11,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,123,Remessa,2023-10-02 00:17:36+00:00,None,None,None,"[{'codigo': 18, 'valor': 40, 'nome': 'outros m...",18.0,motivo_da_remessa,40.0,outros motivos,None
12,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,202,Decretação de falência,2023-09-29 14:45:21+00:00,None,None,None,None,NaN,None,NaN,None,None
13,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,132,Recebimento,2023-09-29 14:05:47+00:00,None,None,None,None,NaN,None,NaN,None,None
14,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,51,Conclusão,2023-06-02 11:42:10+00:00,None,None,None,"[{'codigo': 3, 'valor': 36, 'nome': 'para julg...",3.0,tipo_de_conclusao,36.0,para julgamento,None
15,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,11383,Ato ordinatório,2023-05-16 16:28:56+00:00,None,None,None,None,NaN,None,NaN,None,None
16,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,132,Recebimento,2023-05-16 16:21:10+00:00,None,None,None,None,NaN,None,NaN,None,None
17,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,493,Entrega em carga/vista,2023-05-12 09:52:18+00:00,None,None,None,None,NaN,None,NaN,None,None
18,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,85,Petição,2023-05-09 14:39:30+00:00,None,None,None,"[{'codigo': 19, 'valor': 57, 'nome': 'Petição ...",19.0,tipo_de_peticao,57.0,Petição (outras),None
19,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,92,Publicação,2023-04-17 22:03:18+00:00,None,None,None,None,NaN,None,NaN,None,None

In [59]:
df_movs[['id','numeroProcesso','movimentos_dataHora','movimentos_nome']].head(5)

,id,numeroProcesso,movimentos_dataHora,movimentos_nome
0,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,2024-03-15 12:47:58+00:00,Remessa
1,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,2023-12-13 14:11:17+00:00,Petição
2,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,2023-11-02 02:21:54+00:00,Publicação
3,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,2023-11-01 13:38:53+00:00,Remessa
4,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,2023-11-01 12:42:08+00:00,Ato ordinatório

In [64]:
df_movs.groupby('id').size().reset_index(name='quantidade_movimentos').sort_values(by='quantidade_movimentos', ascending=False)

C:\Users\mooliveira\AppData\Local\Temp\ipykernel_15040\3075928912.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_movs.groupby('id').size().reset_index(name='quantidade_movimentos').sort_values(by='quantidade_movimentos', ascending=False)

                                       id  quantidade_movimentos
0  TJSP_108_G1_10053_00014874419948260445                    706

In [ ]:
lote001['movimentos'][0]

In [66]:
df_movs[df_movs['id'] == 'TJSP_JE_15019982920248260408'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 14 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   id                                          0 non-null      category
 1   numeroProcesso                              0 non-null      object
 2   movimentos_codigo                           0 non-null      int64
 3   movimentos_nome                             0 non-null      object
 4   movimentos_dataHora                         0 non-null      datetime64[ns, UTC]
 5   movimentos_orgaoJulgador                    0 non-null      object
 6   movimentos_orgaoJulgador_codigoOrgao        0 non-null      object
 7   movimentos_orgaoJulgador_nomeOrgao          0 non-null      object
 8   movimentos_complementosTabelados            0 non-null      object
 9   movimentos_complementosTabelados_codigo     0 non-null      float64
 10  movimentos_complementosTabelados_descricao  0 non-null      object
 11  movimentos_complementosTabelados_valor      0 non-null      float64
 12  movimentos_complementosTabelados_nome       0 non-null      object
 13  data_download                               0 non-null      object
dtypes: category(1), datetime64[ns, UTC](1), float64(2), int64(1), object(9)
memory usage: 116.0+ bytes

In [ ]:
lote001[lote001['_id'] == 'TJSP_JE_15019982920248260408'][['movimentos']]

In [ ]:
df_movs[df_movs['_id'] == 'TJSP_JE_15019982920248260408']

### DEPURANDO FUNÇÃO PARA EXTRAÇÃO DOS MOVIMENTOS

In [67]:
df_movs.shape

(706, 14)

#### 1. Verificar colunas esperadas

In [68]:
colunas_esperadas = [
    "_id",
    "movimentos_codigo",
    "movimentos_nome",
    "movimentos_dataHora",
    "movimentos_complementosTabelados",
    "movimentos_complementosTabelados_codigo",
    "movimentos_complementosTabelados_descricao",
    "movimentos_complementosTabelados_valor",
    "movimentos_complementosTabelados_nome",
    "movimentos_orgaoJulgador",
    "movimentos_orgaoJulgador_codigoOrgao",
    "movimentos_orgaoJulgador_nomeOrgao",
]

colunas_faltantes = set(colunas_esperadas) - set(df_movs.columns)

print("Colunas faltantes:", colunas_faltantes if colunas_faltantes else "Nenhuma")

Colunas faltantes: {'_id'}

#### 2. Verificar tipos de dados

In [ ]:
print(df_movs.dtypes)

#### 3. Inspecionar valores não nulos por coluna

- Checar se algum campo está completamente vazio

In [69]:
print(df_movs.notnull().sum())

id                                            706
numeroProcesso                                706
movimentos_codigo                             706
movimentos_nome                               706
movimentos_dataHora                           706
movimentos_orgaoJulgador                        0
movimentos_orgaoJulgador_codigoOrgao            0
movimentos_orgaoJulgador_nomeOrgao              0
movimentos_complementosTabelados              240
movimentos_complementosTabelados_codigo       240
movimentos_complementosTabelados_descricao    240
movimentos_complementosTabelados_valor        240
movimentos_complementosTabelados_nome         240
data_download                                   0
dtype: int64

#### 4. Exibir exemplos onde complementos foram extraídos

In [70]:
df_movs[df_movs["movimentos_complementosTabelados"].notnull()]

,id,numeroProcesso,movimentos_codigo,movimentos_nome,movimentos_dataHora,movimentos_orgaoJulgador,movimentos_orgaoJulgador_codigoOrgao,movimentos_orgaoJulgador_nomeOrgao,movimentos_complementosTabelados,movimentos_complementosTabelados_codigo,movimentos_complementosTabelados_descricao,movimentos_complementosTabelados_valor,movimentos_complementosTabelados_nome,data_download
0,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,123,Remessa,2024-03-15 12:47:58+00:00,None,None,None,"[{'codigo': 18, 'valor': 38, 'nome': 'em grau ...",18.0,motivo_da_remessa,38.0,em grau de recurso,None
1,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,85,Petição,2023-12-13 14:11:17+00:00,None,None,None,"[{'codigo': 19, 'valor': 57, 'nome': 'Petição ...",19.0,tipo_de_peticao,57.0,Petição (outras),None
3,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,123,Remessa,2023-11-01 13:38:53+00:00,None,None,None,"[{'codigo': 18, 'valor': 40, 'nome': 'outros m...",18.0,motivo_da_remessa,40.0,outros motivos,None
7,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,85,Petição,2023-10-27 16:11:23+00:00,None,None,None,"[{'codigo': 19, 'valor': 57, 'nome': 'Petição ...",19.0,tipo_de_peticao,57.0,Petição (outras),None
8,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,60,Expedição de documento,2023-10-27 16:10:39+00:00,None,None,None,"[{'codigo': 4, 'valor': 107, 'nome': 'Certidão...",4.0,tipo_de_documento,107.0,Certidão,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,51,Conclusão,2007-02-06 00:00:00+00:00,None,None,None,"[{'codigo': 3, 'valor': 5, 'nome': 'para despa...",3.0,tipo_de_conclusao,5.0,para despacho,None
672,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,123,Remessa,2006-12-27 00:00:00+00:00,None,None,None,"[{'codigo': 18, 'valor': 37, 'nome': 'em dilig...",18.0,motivo_da_remessa,37.0,em diligência,None
674,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,51,Conclusão,2006-10-18 00:00:00+00:00,None,None,None,"[{'codigo': 3, 'valor': 5, 'nome': 'para despa...",3.0,tipo_de_conclusao,5.0,para despacho,None
675,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,123,Remessa,2006-09-27 00:00:00+00:00,None,None,None,"[{'codigo': 18, 'valor': 37, 'nome': 'em dilig...",18.0,motivo_da_remessa,37.0,em diligência,None
678,TJSP_108_G1_10053_00014874419948260445,00014874419948260445,51,Conclusão,2006-08-08 00:00:00+00:00,None,None,None,"[{'codigo': 3, 'valor': 5, 'nome': 'para despa...",3.0,tipo_de_conclusao,5.0,para despacho,None

#### 5. Verificar valores únicos para campos categóricos

In [71]:
print(df_movs["movimentos_nome"].unique())
print(df_movs["movimentos_complementosTabelados_nome"].unique())

['Remessa' 'Petição' 'Publicação' 'Ato ordinatório' 'Recebimento'
 'Entrega em carga/vista' 'Expedição de documento'
 'Decretação de falência' 'Conclusão' 'Mero expediente' 'Outras Decisões'
 'Documento' 'Desapensamento'
 'Disponibilização no Diário da Justiça Eletrônico' 'Decurso de Prazo'
 'Apensamento' 'Cancelamento de Distribuição']
['em grau de recurso' 'Petição (outras)' None 'outros motivos' 'Certidão'
 'para julgamento' 'em diligência' 'Ofício' 'para decisão'
 'Outros documentos' 'Aviso de recebimento (AR)' 'para despacho' 'Carta'
 'Mandado']

#### 6. Verificar casos com dados aninhados incompletos ou malformados

In [72]:
df_movs[
    df_movs["movimentos_complementosTabelados"].notnull() &
    df_movs["movimentos_complementosTabelados_codigo"].isnull()
]

Empty DataFrame
Columns: [id, numeroProcesso, movimentos_codigo, movimentos_nome, movimentos_dataHora, movimentos_orgaoJulgador, movimentos_orgaoJulgador_codigoOrgao, movimentos_orgaoJulgador_nomeOrgao, movimentos_complementosTabelados, movimentos_complementosTabelados_codigo, movimentos_complementosTabelados_descricao, movimentos_complementosTabelados_valor, movimentos_complementosTabelados_nome, data_download]
Index: []

####  7. Contar registros totais e com complementos

In [73]:
print("Total de movimentos extraídos:", len(df_movs))
print("Com complementos:", df_movs["movimentos_complementosTabelados"].notnull().sum())

Total de movimentos extraídos: 706
Com complementos: 240

#### 8. Verificar se há valores inconsistentes

In [74]:
df_movs[
    df_movs["movimentos_complementosTabelados"].notnull() &
    df_movs["movimentos_complementosTabelados_codigo"].isnull() &
    df_movs["movimentos_complementosTabelados_nome"].isnull()
]

Empty DataFrame
Columns: [id, numeroProcesso, movimentos_codigo, movimentos_nome, movimentos_dataHora, movimentos_orgaoJulgador, movimentos_orgaoJulgador_codigoOrgao, movimentos_orgaoJulgador_nomeOrgao, movimentos_complementosTabelados, movimentos_complementosTabelados_codigo, movimentos_complementosTabelados_descricao, movimentos_complementosTabelados_valor, movimentos_complementosTabelados_nome, data_download]
Index: []

### Variação extração movimentos 

Extração dos campos

- movimentos.orgaoJulgador	
- movimentos.orgaoJulgador.codigoOrgao
- movimentos.orgaoJulgador.nomeOrgao

In [75]:
def extrair_movimentos2(df: pd.DataFrame) -> pd.DataFrame:
    """Extrai campos dos movimentos processuais, incluindo orgaoJulgador e complementosTabelados."""

    movimentos = df[["_id", "movimentos"]].explode("movimentos").reset_index(drop=True)

    movimentos["movimentos_codigo"] = movimentos["movimentos"].apply(lambda x: x.get("codigo") if isinstance(x, dict) else None)
    movimentos["movimentos_nome"] = movimentos["movimentos"].apply(lambda x: x.get("nome") if isinstance(x, dict) else None)
    movimentos["movimentos_dataHora"] = movimentos["movimentos"].apply(lambda x: x.get("dataHora") if isinstance(x, dict) else None)

    # ✅ Extraindo o dicionário bruto do orgaoJulgador
    movimentos["movimentos_orgaoJulgador"] = movimentos["movimentos"].apply(
        lambda x: x.get("orgaoJulgador") if isinstance(x, dict) else None
    )

    # 🔍 Extraindo os subcampos
    movimentos["movimentos_orgaoJulgador_codigoOrgao"] = movimentos["movimentos_orgaoJulgador"].apply(
        lambda x: x.get("codigoOrgao") if isinstance(x, dict) else None
    )
    movimentos["movimentos_orgaoJulgador_nomeOrgao"] = movimentos["movimentos_orgaoJulgador"].apply(
        lambda x: x.get("nomeOrgao") if isinstance(x, dict) else None
    )

    # ✅ ComplementosTabelados
    movimentos["movimentos_complementosTabelados"] = movimentos["movimentos"].apply(
        lambda x: x.get("complementosTabelados") if isinstance(x, dict) else None
    )

    movimentos = movimentos.explode("movimentos_complementosTabelados").reset_index(drop=True)

    movimentos["movimentos_complementosTabelados_codigo"] = movimentos["movimentos_complementosTabelados"].apply(
        lambda x: x.get("codigo") if isinstance(x, dict) else None
    )
    movimentos["movimentos_complementosTabelados_descricao"] = movimentos["movimentos_complementosTabelados"].apply(
        lambda x: x.get("descricao") if isinstance(x, dict) else None
    )
    movimentos["movimentos_complementosTabelados_valor"] = movimentos["movimentos_complementosTabelados"].apply(
        lambda x: x.get("valor") if isinstance(x, dict) else None
    )
    movimentos["movimentos_complementosTabelados_nome"] = movimentos["movimentos_complementosTabelados"].apply(
        lambda x: x.get("nome") if isinstance(x, dict) else None
    )

    # 🎯 Selecionando apenas as colunas desejadas
    colunas_finais = [
        "_id",
        "movimentos_codigo",
        "movimentos_nome",
        "movimentos_dataHora",
        "movimentos_orgaoJulgador",
        "movimentos_orgaoJulgador_codigoOrgao",
        "movimentos_orgaoJulgador_nomeOrgao",
        "movimentos_complementosTabelados",
        "movimentos_complementosTabelados_codigo",
        "movimentos_complementosTabelados_descricao",
        "movimentos_complementosTabelados_valor",
        "movimentos_complementosTabelados_nome"
    ]

    return movimentos[colunas_finais]

In [79]:
lote001['_id']

0     TJSP_JE_15020043620248260408
1     TJSP_JE_15019991420248260408
2     TJSP_JE_15019272720248260408
3     TJSP_JE_15019982920248260408
4     TJSP_JE_15019142820248260408
5     TJSP_JE_15020121320248260408
6     TJSP_JE_15019203520248260408
7     TJSP_JE_15019281220248260408
8     TJSP_JE_15020372620248260408
9     TJSP_JE_15020035120248260408
10    TJSP_JE_15019922220248260408
11    TJSP_JE_15020529220248260408
12    TJSP_JE_15020502520248260408
13    TJSP_JE_15020511020248260408
14    TJSP_JE_15020676120248260408
15    TJSP_JE_15020546220248260408
16    TJSP_JE_15018761620248260408
17    TJSP_G1_15007291220248260583
18    TJSP_JE_15020018120248260408
19    TJSP_JE_15019974420248260408
20    TJSP_JE_15020009620248260408
21    TJSP_JE_15020026620248260408
22    TJSP_JE_15020052120248260408
23    TJSP_JE_15019065120248260408
24    TJSP_JE_15019264220248260408
25    TJSP_JE_15019247220248260408
26    TJSP_JE_15019117320248260408
27    TJSP_JE_15019108820248260408
28    TJSP_JE_15019220520248260408
29    TJSP_JE_15019134320248260408
30    TJSP_JE_15020139520248260408
31    TJSP_JE_15019238720248260408
32    TJSP_JE_15019844520248260408
33    TJSP_JE_15019706120248260408
34    TJSP_JE_15019645420248260408
35    TJSP_JE_15020806020248260408
36    TJSP_G1_15020806020248260408
37    TJSP_JE_15018883020248260408
38    TJSP_JE_15019775320248260408
39    TJSP_JE_15020952920248260408
40    TJSP_JE_15019888220248260408
41    TJSP_JE_15018978920248260408
42    TJSP_JE_15018935220248260408
43    TJSP_JE_15018987420248260408
44    TJSP_JE_15019930720248260408
45    TJSP_JE_00023324020248260408
46    TJSP_JE_00023341020248260408
47    TJSP_JE_15020563220248260408
48    TJSP_JE_15020554720248260408
49    TJSP_JE_15020537720248260408
50    TJSP_G1_10020299720248260411
51    TJSP_G1_15002115320248260411
52    TJSP_JE_15002115320248260411
53    TJSP_G1_10017813420248260411
54    TJSP_G1_10018177620248260411
55    TJSP_G1_10017796420248260411
56    TJSP_G1_10018169120248260411
57    TJSP_G1_10018359720248260411
58    TJSP_G1_10017804920248260411
59    TJSP_G1_10018280820248260411
60    TJSP_G1_10018731220248260411
61    TJSP_G1_10019156120248260411
62    TJSP_G1_10018852620248260411
63    TJSP_G1_10017752720248260411
64    TJSP_G1_10018445920248260411
65    TJSP_G1_10018402220248260411
66    TJSP_G1_10018410720248260411
67    TJSP_G1_10017761220248260411
68    TJSP_G1_00009942220248260411
69    TJSP_G1_10018090220248260411
70    TJSP_G1_10019112420248260411
71    TJSP_G1_10017787920248260411
72    TJSP_G1_10019658720248260411
73    TJSP_G1_10019805620248260411
74    TJSP_G1_10018081720248260411
75    TJSP_G1_10019009220248260411
76    TJSP_G1_10018558820248260411
77    TJSP_G1_00009925220248260411
78    TJSP_G1_10018662020248260411
79    TJSP_G1_10018670520248260411
80    TJSP_G1_10019761920248260411
81    TJSP_G1_10017700520248260411
82    TJSP_G1_10019199820248260411
83    TJSP_G1_10018567320248260411
84    TJSP_G1_10019363720248260411
85    TJSP_G1_10018991020248260411
86    TJSP_G1_10018125420248260411
87    TJSP_G1_10018150920248260411
88    TJSP_G1_10018766420248260411
Name: _id, dtype: object

In [76]:
df = extrair_movimentos2(lote001)

In [77]:
df

,_id,movimentos_codigo,movimentos_nome,movimentos_dataHora,movimentos_orgaoJulgador,movimentos_orgaoJulgador_codigoOrgao,movimentos_orgaoJulgador_nomeOrgao,movimentos_complementosTabelados,movimentos_complementosTabelados_codigo,movimentos_complementosTabelados_descricao,movimentos_complementosTabelados_valor,movimentos_complementosTabelados_nome
0,TJSP_JE_15020043620248260408,26,Distribuição,2024-07-16T17:24:07.000Z,None,None,None,"{'codigo': 2, 'descricao': 'tipo_de_distribuic...",2.0,tipo_de_distribuicao_redistribuicao,2.0,sorteio
1,TJSP_JE_15020043620248260408,581,Documento,2024-07-16T17:28:18.000Z,None,None,None,"{'codigo': 4, 'descricao': 'tipo_de_documento'...",4.0,tipo_de_documento,80.0,Outros documentos
2,TJSP_JE_15020043620248260408,11383,Ato ordinatório,2024-07-17T10:42:52.000Z,None,None,None,None,NaN,None,NaN,None
3,TJSP_JE_15020043620248260408,60,Expedição de documento,2024-07-17T10:43:09.000Z,None,None,None,"{'codigo': 4, 'descricao': 'tipo_de_documento'...",4.0,tipo_de_documento,107.0,Certidão
4,TJSP_JE_15020043620248260408,85,Petição,2024-07-17T20:11:25.000Z,None,None,None,"{'codigo': 19, 'descricao': 'tipo_de_peticao',...",19.0,tipo_de_peticao,57.0,Petição (outras)
...,...,...,...,...,...,...,...,...,...,...,...,...
2668,TJSP_G1_10018766420248260411,123,Remessa,2024-09-25T05:44:58.000Z,None,None,None,"{'codigo': 18, 'descricao': 'motivo_da_remessa...",18.0,motivo_da_remessa,40.0,outros motivos
2669,TJSP_G1_10018766420248260411,92,Publicação,2024-09-26T01:16:49.000Z,None,None,None,None,NaN,None,NaN,None
2670,TJSP_G1_10018766420248260411,60,Expedição de documento,2024-10-05T07:55:27.000Z,None,None,None,"{'codigo': 4, 'descricao': 'tipo_de_documento'...",4.0,tipo_de_documento,107.0,Certidão
2671,TJSP_G1_10018766420248260411,848,Trânsito em julgado,2024-10-22T15:20:55.000Z,None,None,None,None,NaN,None,NaN,None
2672,TJSP_G1_10018766420248260411,246,Definitivo,2024-10-22T15:23:14.000Z,None,None,None,None,NaN,None,NaN,None

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
print(df.notnull().sum())

In [ ]:
# Verifica se ao menos um movimento possui 'orgaoJulgador'
existe_orgaoJulgador = lote001['movimentos'].explode().dropna().apply(
    lambda x: isinstance(x, dict) and 'orgaoJulgador' in x
).sum()

print(f"Número de movimentos com 'orgaoJulgador': {existe_orgaoJulgador}")